// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a session connection (advisory locks), which the
    // transaction pooler on 6543 doesn't support. DIRECT_URL points at the
    // session pooler; DATABASE_URL stays the serverless-safe runtime URL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
