"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";

export async function saveSettings(formData: FormData) {
  const get = (key: string) => String(formData.get(key) ?? "");

  await prisma.siteSettings.upsert({
    where: { id: 1 },
    create: {
      id: 1,
      name: get("name"),
      tagline: get("tagline"),
      phone1: get("phone1"),
      phone2: get("phone2"),
      whatsapp: get("whatsapp"),
      email: get("email"),
      addressLine1: get("addressLine1"),
      addressLine2: get("addressLine2"),
      instagram: get("instagram"),
      linkedin: get("linkedin"),
      facebook: get("facebook"),
      heroEyebrow: get("heroEyebrow"),
      heroHeadlineWhite: get("heroHeadlineWhite"),
      heroHeadlineGreen: get("heroHeadlineGreen"),
      heroSubtext: get("heroSubtext"),
      heroImage: get("heroImage"),
      teamImage: get("teamImage"),
      footerLogo: get("footerLogo"),
      servicesEyebrow: get("servicesEyebrow"),
      servicesHeadline: get("servicesHeadline"),
      heroCtaLabel: get("heroCtaLabel"),
      heroSecondaryCtaLabel: get("heroSecondaryCtaLabel"),
      ctaEyebrow: get("ctaEyebrow"),
      ctaText: get("ctaText"),
      ctaButtonLabel: get("ctaButtonLabel"),
      aboutEyebrow: get("aboutEyebrow"),
      aboutHeadline: get("aboutHeadline"),
      aboutText1: get("aboutText1"),
      aboutText2: get("aboutText2"),
      aboutStat1Value: get("aboutStat1Value"),
      aboutStat1Label: get("aboutStat1Label"),
      aboutStat2Value: get("aboutStat2Value"),
      aboutStat2Label: get("aboutStat2Label"),
      aboutImage1: get("aboutImage1"),
      aboutImage2: get("aboutImage2"),
    },
    update: {
      name: get("name"),
      tagline: get("tagline"),
      phone1: get("phone1"),
      phone2: get("phone2"),
      whatsapp: get("whatsapp"),
      email: get("email"),
      addressLine1: get("addressLine1"),
      addressLine2: get("addressLine2"),
      instagram: get("instagram"),
      linkedin: get("linkedin"),
      facebook: get("facebook"),
      heroEyebrow: get("heroEyebrow"),
      heroHeadlineWhite: get("heroHeadlineWhite"),
      heroHeadlineGreen: get("heroHeadlineGreen"),
      heroSubtext: get("heroSubtext"),
      heroImage: get("heroImage"),
      teamImage: get("teamImage"),
      footerLogo: get("footerLogo"),
      servicesEyebrow: get("servicesEyebrow"),
      servicesHeadline: get("servicesHeadline"),
      heroCtaLabel: get("heroCtaLabel"),
      heroSecondaryCtaLabel: get("heroSecondaryCtaLabel"),
      ctaEyebrow: get("ctaEyebrow"),
      ctaText: get("ctaText"),
      ctaButtonLabel: get("ctaButtonLabel"),
      aboutEyebrow: get("aboutEyebrow"),
      aboutHeadline: get("aboutHeadline"),
      aboutText1: get("aboutText1"),
      aboutText2: get("aboutText2"),
      aboutStat1Value: get("aboutStat1Value"),
      aboutStat1Label: get("aboutStat1Label"),
      aboutStat2Value: get("aboutStat2Value"),
      aboutStat2Label: get("aboutStat2Label"),
      aboutImage1: get("aboutImage1"),
      aboutImage2: get("aboutImage2"),
    },
  });

  revalidatePath("/");
  revalidatePath("/admin/configuracoes");
}
